### ISSUE TITLE
Google Colab version

### ISSUE THREAD

**Issue by nklapste** [chamik/petthex#1]
I recreated this as a google colab notebook! 

https://colab.research.google.com/drive/1xejUjlPtmKxFhYUxUjYKrIk5VEV2gnx6?usp=sharing

I was wondering if you wanted to use this as a quick way to run this code online!

**Comment by chamik** [comment]
Hell yeah! This is awesome, I'm glad that someone else is making use of this. Thank you! <3

**Comment by nklapste** [comment]
Feel free to copy/embed/use as you please! 

Thanks again for making the python code!

**Comment by chamik** [comment]
I've added the link to README, thank you again!
